# Generated by Django 5.0.6 on 2024-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_suburbio', '0003_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
